name: kickoff
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1            # For API calls
  shared_preferences: ^2.2.2 # For local storage
  provider: ^6.0.2        # Add provider package for state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/manunited.png  # Add this line to include your logo image
    - assets/images/chelsea.png  # Add this line to include your logo image
    - assets/images/arsenal.png  # Add this line to include your logo image
    - assets/images/astonvilla.png  # Add this line to include your logo image
    - assets/images/crystalpalace.png  # Add this line to include your logo image
    - assets/images/everton.png  # Add this line to include your logo image
    - assets/images/fulham.png  # Add this line to include your logo image
    - assets/images/liverpool.png  # Add this line to include your logo image
    - assets/images/mancity.png  # Add this line to include your logo image
    - assets/images/newcastle.png  # Add this line to include your logo image
    - assets/images/southampton.png  # Add this line to include your logo image
    - assets/images/spurs.png  # Add this line to include your logo image
    - assets/images/westham.png  # Add this line to include your logo image
